# .pre-commit-config.yaml

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.2"  # Use the latest stable version of ruff
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
